change condition and secrets name

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -17,7 +17,7 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Set up JDK
-        uses: actions/setup-java@v2
+        uses: actions/setup-java@v1
         with:
           java-version: "11"
 
@@ -32,19 +32,21 @@ jobs:
       - name: Build and analyze with SonarQube
         run: |
           mvn clean install sonar:sonar \
-            -Dsonar.host.url=${{ secrets.SONARQUBE_SERVER_URL }} \
-            -Dsonar.login=${{ secrets.SONARQUBE_AUTH_TOKEN }} \
-            -Dsonar.projectKey=QulityGateTest
+            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
+            -Dsonar.login=${{ secrets.SONAR_LOGIN_TOKEN }} \
+            -Dsonar.projectKey=${{ secrets.PROJECT_KEY }}
         env:
-          SONARQUBE_SERVER_URL: ${{ secrets.SONARQUBE_SERVER_URL }}
-          SONARQUBE_AUTH_TOKEN: ${{ secrets.SONARQUBE_AUTH_TOKEN }}
+          SONARQUBE_SERVER_URL: ${{ secrets.SONAR_HOST_URL }}
+          SONARQUBE_AUTH_TOKEN: ${{ secrets.SONAR_LOGIN_TOKEN }}
 
       - name: Check SonarQube Quality Gate status
         run: |
-          STATUS=$(curl -s "${{ secrets.SONARQUBE_SERVER_URL }}/api/qualitygates/project_status?projectKey=${{ secrets.PROJECT_KEY }}" \
-                    -u "${{ secrets.SONARQUBE_PROJECT_TOKEN }}" | jq -r .projectStatus.status)
+          STATUS=$(curl -s "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ secrets.PROJECT_KEY }}" \
+                    -u "${{ secrets.SONAR_TOKEN }}" | jq -r .projectStatus.status)
           echo "SonarQube Quality Gate status: $STATUS"
           if [ "$STATUS" != "OK" ]; then
-            echo "Quality Gate check failed!"
-            exit 1
+            echo "SonarQube Quality Gate Failed !!"
+          exit 1
+          else
+            echo "SonarQube Quality Gate passed !!" 
           fi
